### ISSUE TITLE
Glitched Commas in Quest Text

### ISSUE THREAD

**Issue by Underplayer97** [Midnight145/blightfall-issue-tracker#10]
I have found a couple of symbols that I believe is not meant to be there and more supposed to be a comma. I have just started a new pack so I might miss (many) of the bugged text but the ones that I have found right now is:

**Chapter 1:**
- Dr. Diyo's Modular Tools
- Tools to Build the Parts

If I found any more, I might add them into the comments

**Comment by Midnight145** [comment]
Went ahead and fixed apostrophes for all quests in the tutorial line, which _should_ be the only things that are broken. Please post any that you find though, in case I missed some.

**Comment by Jaari** [comment]
![Screenshot](https://user-images.githubusercontent.com/10313979/216499809-617bcc0d-a1fb-470f-a94b-d9d0a059eeb2.png)

Saw this when viewing aspects too. Might also be related to Issue #7

**Comment by Midnight145** [comment]
> ![Screenshot](https://user-images.githubusercontent.com/10313979/216499809-617bcc0d-a1fb-470f-a94b-d9d0a059eeb2.png)
> 
> Saw this when viewing aspects too. Might also be related to Issue #7

A mod that fixes a lot of quirks/issues with thaumic-nei is going to be included in the next update, which should *hopefully* fix that. The extra tab might be there, not sure, but in theory it'll fix the text.

**Comment by Midnight145** [comment]
Closing this for now, feel free to reopen if you find any more.
