### ISSUE TITLE
Marble currently cannot be crafted into its chiselable state

### ISSUE THREAD

**Issue by KyokoDolls** [Midnight145/blightfall-issue-tracker#100]
The recipe for crafting marble into the chisel version currently does not work, due to the recipe yielding marble bricks instead. My guess is the recipe for marble bricks is overriding it.

**Comment by koopa02** [comment]
i think u have to just manually chisel it in the chisel item gui

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightfall-configs/commit/bc71b8c4a2f326d870e234f4753435fd366bafe7
