### ISSUE TITLE
Thaumcraft's Bone Bow research can't be unlocked while scanning prerequisite items in inventory

### ISSUE THREAD

**Issue by LegioInformatica** [Midnight145/blightfall-issue-tracker#101]
The Bone Bow research in the Thaumonomicon unlocks only when the prerequisite items (bone, bow) are scanned in-world, not from the inventory screen. Scanning from inventory actually prevents the player from unlocking the research in this way due to items being scannable once.

Workaround:

If you haven't scanned a bow or a bone yet, take care to do it in-world, not from the inventory screen.

If you have already scanned these items, you can revert the scan by deleting their keys from the SCAN.OBJECTS section in the save file data. Deleting "@-1150180019"(bone) and "@-1283802175"(bow) should allow you to scan them again using the in-world method.

**Comment by LegioInformatica** [comment]
Detailed instructions for reverting the scan in the save data:

Use the NBT explorer of your choosing (I used NBT studio, NBTExplorer should work it didn't work for me), then go into your world save's folder, go into the playerdata folder, open the <mcusername>.thaum file in NBT studio, then expand the THAUMCRAFT.SCAN.OBJECTS section where you'll then search the bone and bow scanning with ctrl+f and then input the codes one by one, after you've deleted both of the entries, hit ctrl+s to save the modifications and you can now load back into your world and scan both of those items in-world so you can get the bow of bone research. If something breaks for some reason (which it didn't for me), the <mcusername>.thaumback is the backup file which you can rename to .thaum to have everything be as it was before you edited anything

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/TechnicPack/Technic/commit/37115bb2aca695c9efea023b56b7a4eed6293ee3)
