### ISSUE TITLE
add a clearing distance from the machine 

### ISSUE THREAD

**Issue by koopa02** [Midnight145/blightfall-issue-tracker#103]
please can you add a clearing distance from the dawn machine when it it supplied with cognitio because i have no idea, nor does it seem like it is working, or whether it is working at all with all supplies maxxed out

**Comment by tiflu** [comment]
what is your issue? cognitio is used instead of other essentia when a cleansed chunk is attempted to be cleansed again.

**Comment by koopa02** [comment]
I was under the impression that cognitio stopped it picking chunks at random and clearing in a spiral instead. Either ive cleared so much space that its still tryna catch up or its not working at all

**Comment by tiflu** [comment]
please read the books carefully

**Comment by koopa02** [comment]
which book?

**Comment by koopa02** [comment]
correction i meant ordo essence

**Comment by koopa02** [comment]
also tiflu given previous issues can you not get involved in this

**Comment by tiflu** [comment]
if you're having issues getting the dawn machine to work, you should ask for help on the blightfall discord, technic discord, or blightfall subreddit. the github is mostly intended for bug reports and feature requests

**Comment by koopa02** [comment]
This _is_ a feature request

**Comment by tiflu** [comment]
please clarify what you are requesting? the dawn machine has a cleaning radius, of 16(?) chunks or so at base and the entire map with ordo

**Comment by tiflu** [comment]
sorry, with aer*

**Comment by koopa02** [comment]
i am asking for it to be added to the dawn machine how far from the dawn machine it is clearing when supplied with both ordo and cognitio, ordo cause it  causes the spiral and cognito cause it stops reclearing already cleared area

**Comment by koopa02** [comment]
the only clearing ive noticed while having a dawn machine running, is the area ive manually cleared with a purity wand focus

**Comment by tiflu** [comment]
ordo nor cognitio change the overall area the machine clears. it's likely that you are not running the machine correctly. if you're using aer essentia, it's possible it's clearing chunks that you're not in.

**Comment by maddyfoxmom** [comment]
ok let's clear things up
cognitio essentia prevents cleaning of chunks that have already been purified
ordo essentia causes the dawn machine to clean in an outwards spiral from the center instead of randomly
aer essentia increases the range of the dawn machine to the entire map
the dawn machine will need different amounts of these essentia to run properly, which can be discounted by providing it mana and life points
provided that you are giving the dawn machine the proper and sufficient amounts of essentia, and it is still not working as desired, then that's a bug

**Comment by koopa02** [comment]
I had it fully set up with it on supplied with mana and rf will all input maxxed the issue is not with it being set up wrongis with being inable to know if it is clearing space when it doesnt seem to be

**Comment by koopa02** [comment]
Ive now blown up my dawn machine deliberately and will be manually clearing the map with a maxxed out purity focus

**Comment by koopa02** [comment]
My request was for a feature to be added for the machine to display where it is currently clensing while provided with both ordo and congitio, the two aspects that controll what gets cleared and how it does said clear, but obviously this isnt something you are willing to do

**Comment by koopa02** [comment]
Fml

**Comment by maddyfoxmom** [comment]
I'm not a developer and neither is tiflu, but I do agree with the suggestion and will bring it to the appropriate devs

**Comment by koopa02** [comment]
Oh its fine i dont plan to play blightfall again as its just become a chore now

**Comment by Midnight145** [comment]
Sorry about that

To clarify, are you asking for some kind of indicator where you can check to see which chunk coordinates the dawn machine is currently cleaning? Like, either something along the lines of the way the essentia currently pops up above the cyber totem or a message in chat?

**Comment by koopa02** [comment]
Precisely that lol cause then at least there is a direct way to check that your machine isnt bugged, cause u can go to those coords and see if its working. Or even changing it so that at the cost of both ordo and cognitio it allows you to set the coordinates to clear to and from like the rf tools builder does with the quarry shape cards

**Comment by Midnight145** [comment]
Alright, cool. I'll likely add something where if you right-click on the cyber totem, it'll show the chunk coordinates in chat, or possibly a special interaction with the blink focus where if you right-click on the cyber totem with the blink focus, you teleport to where it's cleaning.

Do you have a preference on which?

**Comment by koopa02** [comment]
Personally it think it would acc be cool for both so that those who love thaum and go deep into it have a unique interaction for that but those who dont can still at least go there manually

**Comment by Midnight145** [comment]
alright! I can try to get that done later today!

**Comment by koopa02** [comment]
Its like 2am for me rn so ill probs reply later on

**Comment by Midnight145** [comment]
sounds good!

**Comment by Midnight145** [comment]
For now I've added it where if you shift + right click on the dawn machine, it'll show in chat both the chunk coords and relative block coordinates of where is currently being cleaned. In the future I might add something with the blink focus, but not right now I don't think.
