### ISSUE TITLE
'Sort by number of times eaten' in the Cooking For Blockheads table immediately crashes when clicked

### ISSUE THREAD

**Issue by atomic-cherry** [Midnight145/blightfall-issue-tracker#105]
Can provide a log if needed. It's pretty easily reproducible, though.

**Comment by Midnight145** [comment]
oof, apparently I only imagined fixing this. I _might_ have a cooking for blockheads build ready, if you don't mind testing it. Unsure if I actually finished it though.

**Comment by Midnight145** [comment]
github won't let me upload a jarfile so I had to compress it, try this build

it doesn't crash, though I don't know if it actually works properly.

[CookingForBlockheads-1e90af0-spiceoflife-compat+1e90af08fd-dirty.zip](https://github.com/Midnight145/blightfall-issue-tracker/files/15031327/CookingForBlockheads-1e90af0-spiceoflife-compat%2B1e90af08fd-dirty.zip)

**Comment by atomic-cherry** [comment]
Yep, tested the edited jar out and the sorting works. Hopefully nothing else broke that I can see.

**Comment by Midnight145** [comment]
oh cool, things actually sort?

**Comment by atomic-cherry** [comment]
~~Haven't tested with every food, but it mostly sorts properly on my test world.~~

Thought it did. But I tested further and it's not actually being sorted properly. It seems to just be alphabetical with the inedible ingredients moved to the bottom.

**Comment by Midnight145** [comment]
[CookingForBlockheads-1e90af0-spiceoflife-compat+1e90af08fd-dirty.zip](https://github.com/Midnight145/blightfall-issue-tracker/files/15031707/CookingForBlockheads-1e90af0-spiceoflife-compat%2B1e90af08fd-dirty.zip)

**Comment by atomic-cherry** [comment]
I can confirm that that one works and sorts properly on my end.

**Comment by Midnight145** [comment]
Sweet, tysm

**Comment by Midnight145** [comment]
pull request made [here](https://github.com/GTNewHorizons/CookingForBlockheads/pull/44), once that's accepted I'll close this

**Comment by Midnight145** [comment]
fixed in [this cfb release](https://github.com/GTNewHorizons/CookingForBlockheads/releases/tag/1.3.4-GTNH)
