### ISSUE TITLE
Golem bug with Datawatchers

### ISSUE THREAD

**Issue by KuboSE** [Midnight145/blightfall-issue-tracker#106]
Playing on a Blightfall server, I started seeing an error message after I set up some golems to run a tree farm for power generation with Endoflames. The error only happens when the golems are actively doing something (so not when they are standing around waiting for something to interact with)

After some testing, I have found that 2 alchemy golems and 1 wood chopping golem running at the same time throws no errors, while a single gather golem being active throws the error every few seconds. A similar issue that was posted on the TC github at one point seems to say that this is caused by a mod adding more datawatchers to entities. It doesn't crash the game or server, but it does seem to potentially cause some issues with the golems responding to tasks in a reasonable amount of time, and potentially some performance issues/server lag issues.
![golemDataWatcherBug](https://github.com/Midnight145/blightfall-issue-tracker/assets/7027713/6de82d5d-ae0a-4f67-b9f7-451726e24a38)

**Comment by Midnight145** [comment]
Likely not an issue I can fix, it's also possible that it'll be resolved by other mod updates
