### ISSUE TITLE
Bugged Apostraphe

### ISSUE THREAD

**Issue by Underplayer97** [Midnight145/blightfall-issue-tracker#110]
![image](https://github.com/Midnight145/blightfall-issue-tracker/assets/66751151/23a5d909-ae7b-4a3b-9239-8ff2047a019e)
Inside the Xenobiologist questline in the quest "Cloth Samples - Anthropology"

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightfall-configs/commit/b2db89871534923e70bbd312ee18bf0d42e88d1e
