### ISSUE TITLE
Items with Mana can't be properly used as ingredients

### ISSUE THREAD

**Issue by atomic-cherry** [Midnight145/blightfall-issue-tracker#111]
![2024-05-02_10 13 20](https://github.com/Midnight145/blightfall-issue-tracker/assets/37892647/0a71ff88-d726-4c4e-84cd-e769b7852bee)

I noticed this before when trying to make a Greater Band of Mana (I had to cheat delete the ingredients and spawn one in when it didn't work) but shown above is me trying to make a Mana Mirror. If the tablet is charged with any mana (1% to full) the craft doesn't work.

![2024-05-02_10 21 39](https://github.com/Midnight145/blightfall-issue-tracker/assets/37892647/588a75a4-3396-4043-84f6-5935f438a46f)

Now I went away from my base and emptied the tablet and it works fine.

**Comment by Midnight145** [comment]
will be fixed next patch!
