### ISSUE TITLE
A few minor issues with certain ores

### ISSUE THREAD

**Issue by LegioInformatica** [Midnight145/blightfall-issue-tracker#113]
There are a couple inconsistencies related to ores - this is really nitpicky and should be considered low-priority.

The material entry for Nether Quartz in the "Mining and Resource Collection" book is a bit misleading. It leads you to believe Nether Quartz Ore is in the desert area, and that you need at least soft metal mining level to mine it. What you actually get is a Terrestial variant of Nether Quartz, which has no mining level requirement.
![Quartz1](https://github.com/Midnight145/blightfall-issue-tracker/assets/117222631/b0ad45bb-0b65-4920-b56a-bf07c700a141)

Copper ore, tin ore, silver ore and platinum ore show no recipes related to Thermal Expansion in NEI, despite being able to be pulverized, smelted in an Induction Smelter, etc.

Phosphorite ore (the ore, not phosphorus as an item) has no interactions with the pulverizer. This is strange, because the ores of similar minerals (sulfur ore, magnesium ore, saltpeter ore, etc.) can be pulverized, only phosphorite ore seems to be an exception to this rule.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/c68c37adf733fdf42d5d215041184af138dc64e5)
