### ISSUE TITLE
New Recipe Request - Make Gold/Iron tools the same way you can make Diamond Tools

### ISSUE THREAD

**Issue by atomic-cherry** [Midnight145/blightfall-issue-tracker#115]
Since you frequently need the standard Gold and Iron tools to make MFR machines (+some other recipes), it just makes sense to be able to craft them in the same way you make the Diamond tools, through Blood Magic. Waiting for them to refresh in The Supplier tab isn't really feasible when you need multiple machines and time is your bottleneck.

**Comment by Midnight145** [comment]
added in https://github.com/Midnight145/blightfall-configs/commit/00bc9ea21b431bb2c242c7117600ebadb4e442df
