### ISSUE TITLE
Thermal Cell Refill HQM Progression

### ISSUE THREAD

**Issue by Xefyr0** [Midnight145/blightfall-issue-tracker#116]
In short, there have been multiple complaints where energy cell refill quests from the Supplier were locked due to not refilling the previous tier(s) of energy cell.

![energy_cells](https://github.com/Midnight145/blightfall-issue-tracker/assets/78383477/c810b8f4-a139-4fac-abc4-934116b98f39)

This could be resolved by altering the unlock requirements to [ having the corresponding tier of cell in the inventory ] or removing the unlock requirements entirely.

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightfall-configs/commit/b2db89871534923e70bbd312ee18bf0d42e88d1e
