### ISSUE TITLE
Damage when Teleporting to The Jaded

### ISSUE THREAD

**Issue by Xefyr0** [Midnight145/blightfall-issue-tracker#119]
When teleporting aboard The Jaded, the player teleports such that their head is inside a block.
This causes 1/2 heart of suffocation damage, and then shoves them downwards out of the block.

The simplest and least obtrusive way to fix the issue would be to do something like ![this](https://github.com/Midnight145/blightfall-issue-tracker/assets/78383477/e0cdff9b-dea3-43dc-a294-54b7d2b7ab43) where the suffocating blocks are converted to top slabs.

**Comment by Midnight145** [comment]
If the map ever gets updated again, I'll do this, but its not something that I think needs to be patched via code. If you want, you can make a pull request to Midnight145/blightfall-filefix which has misc patches, but it's not something that I personally think is high priority enough.

**Comment by Xefyr0** [comment]
I see the corresponding region file is in the repo you linked, do I just merge the changes to that region file from loading the world, adding in the slabs & logging out?

Also, how does Drop Pod Beta's ladder factor into this?

**Comment by Midnight145** [comment]
Is that the same region file? I wanna say that region file is unrelated.

In a perfect world, you'd just setblock the slabs since it's only a few blocks

**Comment by Xefyr0** [comment]
Yeah, the existing one has data for the last millenium

I'll try and figure out how to /setblock for a region that is immediately loaded because I spawn there when the world is made?

Probably by moving to a different region, copying the region file over from the world template, using the command, and then exporting the result

**Comment by Xefyr0** [comment]
Status update: Looks like the commands are
/setblock -973 152 -1048 minecraft:stone_slab 15
/setblock -973 152 -1047 minecraft:stone_slab 15
/setblock -973 152 -1046 minecraft:stone_slab 15

And
/setblock -949 148 -1048 TConstruct:decoration.stoneladder 2
If we also want to do the missing Beta ladder since it's the same region

**Comment by Xefyr0** [comment]
I followed the steps above, tested it by manually copying the region file to the flans directory, and it works when creating a new world.
Made a pull request with the new region file on [Midnight145/blightfall-filefix](https://github.com/Midnight145/blightfall-filefix).
