### ISSUE TITLE
NEI recipes don't show usage or recipe for Smeltery Liquids while inside NEI recipes

### ISSUE THREAD

**Issue by IKnewOne** [Midnight145/blightfall-issue-tracker#12]
Steps to reproduce: 
1. Look for usage of an ore or any other item that can smelt into a liquid in a Smeltery
2. Jump to "smeltery melting" page
3. Try using "Recipe" or "Usage" bind, or try to right/left click on it in recipe mode. 
NEI will not react to anything
![image](https://user-images.githubusercontent.com/41551327/216642186-9290d95d-9d91-47ce-94ef-de821d244f3b.png)

**Comment by Midnight145** [comment]
Will be fixed in next release by updating NEI
