### ISSUE TITLE
[Suggestion] Add Neodymium, FastCraft, Sonomagy, Smooth Font, WAILA Plugins, Fast Leaf Decay, ASMC, SerializationIsBad, ITLT, Target Dummy

### ISSUE THREAD

**Issue by xJon** [Midnight145/blightfall-issue-tracker#126]
Also, might be nice to set `checkVersion` to `false` in `\modpacks\blightfall\config\aroma1997\Aroma1997Core.cfg` and possibly change some HQM configs to avoid these messages print to chat every time:
![image](https://github.com/user-attachments/assets/3ae0df9a-4471-4b8a-8d35-8ee6a5743d8d)

**Comment by Midnight145** [comment]
Serializationisbad is being added next patch, as well as the config change. I'll look into ITLT, and I'll try and figure out where that hqm config line is, though I seem to remember trying to disable it in the past, though I might be wrong.

**Comment by xJon** [comment]
@Midnight145 Also is it intentional you start with 2 questing books?

**Comment by Midnight145** [comment]
No, but I'm also not entirely sure why this happens. Might be that one config line that gives you one

**Comment by xJon** [comment]
For ITLT, you can check out The 1.7.10 Pack for example configs.

**Comment by xJon** [comment]
Also suggesting to add Neodymium, FastCraft, both have wide compatibility with old 1.7.10 modpacks, and OptiFine.

**Comment by JL2210** [comment]
I'm working on getting Angelica and Hodgepodge to work. Those are incompatible with FastCraft and still actively developed

**Comment by xJon** [comment]
@JL2210 I suggested Neodymium and FastCraft as they can be "tossed in" as-is with minimal effort, however if people are willing to put in the work then sure, those can probably be even better.

**Comment by xJon** [comment]
Added suggestion for Smooth Font.

**Comment by xJon** [comment]
Added suggestion for Sonomagy, WAILA Plugins, Fast Leaf Decay, and ASMC.

Regarding Fast Leaf Decay, you could consider configuring it so the decay is not *that* fast, but still not as slow as default.

**Comment by xJon** [comment]
Added suggestion for Target Dummy (https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm).

**Comment by BillyBobJoe12345** [comment]
> No, but I'm also not entirely sure why this happens. Might be that one config line that gives you one

It is exactly why that happens, you can test by making a new world after changing the config
