### ISSUE TITLE
Cached map data in singleplayer/multiplayer worlds

### ISSUE THREAD

**Issue by xJon** [Midnight145/blightfall-issue-tracker#127]
I didn't look into it too much, but there seems to be a mechanism that includes the full VoxelMap cached map data for singleplayer worlds. It'd be great if this can be applied to multiplayer worlds as well, regardless of the server IP.
Searching it in Google it seems that some people playing multiplayer were unaware it was a feature, and were disappointed the explored areas were reset when the server IP changed.

**Comment by xJon** [comment]
Currently it's still possible but quite clunky (to start a new singleplayer world, and copy over the cached map data to the server folder).

**Comment by Midnight145** [comment]
I actually talked to Talonos about this a while ago, the map being filled out in singleplayer is more of an unavoidable bug. Multiplayer is actually the correct behavior, but due to voxelmap going off generated chunks in singleplayer, all of the map chunks from lockdown are cached already.

**Comment by xJon** [comment]
Oh, that's quite bizarre. Good to know what's intentional and what's not. Maybe fixable with Mixins?

**Comment by Midnight145** [comment]
Hard to say. I'm not *too* familiar with how it works, I looked into decompiling it once but it seems heavily obfuscated, unsure if it's just the nature of liteloader or not.

**Comment by xJon** [comment]
Ah yeah I think LiteLoader VoxelMap is highly obfuscated. Might be worth asking @glowredman who made worked on 1.7.10 https://github.com/glowredman/VoxelMapFixer a couple of years ago.

**Comment by JL2210** [comment]
The 1.12 forge version isn't obfuscated, I've been using it as a basis to work on bugs in the 1.7 version.

glowredman also worked on mixins currently in Hodgepodge iirc

**Comment by xJon** [comment]
@JL2210 You have fixed bugs in the 1.7 version?

**Comment by JL2210** [comment]
Still working on it. There's only really one bug important enough that I want to fix, and that's that with Angelica, all the waypoints show up really dark

**Comment by JL2210** [comment]
JourneyMap Unlimited can do the whole map iirc. Maybe check that out

**Comment by xJon** [comment]
Personally I wouldn't like seeing VoxelMap being replaced.

**Comment by glowredman** [comment]
> Ah yeah I think LiteLoader VoxelMap is highly obfuscated. Might be worth asking @glowredman who worked on 1.7.10 https://github.com/glowredman/VoxelMapFixer a couple of years ago. https://github.com/GTNewHorizons/Navigator might also be relevant?

VoxelMapFixer is no longer maintained, I merged all fixes into Hodgepodge.
