### ISSUE TITLE
NEI recipes don't show usage for Smeltery Liquids

### ISSUE THREAD

**Issue by IKnewOne** [Midnight145/blightfall-issue-tracker#13]
NEI recipes don't show usage for Smeltery Liquids, no casting, no tools

**Comment by Midnight145** [comment]
Sorry, I'm not sure what the difference between this and issue #12 is. Can you elaborate?

**Comment by IKnewOne** [comment]
In #12 you can't see liquid usage if you try to look at it by starting at ingot > smeltery liquid, you couldn't click on the liquid to see the usage of it. If you were to look at usage of liquid directly from NEI, you would be able to see what it can alloy with, but you can't see usage of those liquids in the casts.

**Comment by Midnight145** [comment]
Ahh, alright--I see now. Will look into it, it might be due to the way this version of NEI handles fluids though, I'm not sure.

**Comment by Midnight145** [comment]
unfortunately as far as I can tell, this is an issue with gtnh's nei

you might be able to have success if you open an issue there, but I'm not familiar enough with modding to be able to fix it myself
