### ISSUE TITLE
Automagy Shard Slivers Cannot be crafted

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [Midnight145/blightfall-issue-tracker#132]
Title. In the current version, or at least mine, automagy slivers cannot be crafted. To my non-coding ass, it seems that the input for the craft has been oredicted, or isn't using meta ID, causing all the recipe to have order shard as the input, but output the proper slivers. In the end, in the actual arcane table, order shard makes aer slivers.

**Comment by LazyFleshWasTaken** [comment]
Huh, seems to be fine after an instance restart? Weird.

**Comment by JL2210** [comment]
Yeah, that just happens with recipes sometimes, for some reason... I wasn't able to craft burnt quartz for a while because of it
