### ISSUE TITLE
mods with active upstream

### ISSUE THREAD

**Issue by JL2210** [Midnight145/blightfall-issue-tracker#133]
AppleCore: https://github.com/GTNewHorizons/AppleCore
Applied Energistics 2: https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial
ArchaicFix: https://modrinth.com/mod/archaicfix
Baubles Expanded, drop-in for Baubles (confirmed working by me) https://github.com/jss2a98aj/Baubles-Expanded
Chisel is messy, the blocks are present but they all have the wrong IDs. Don't recommend
CodeChickenCore: https://github.com/GTNewHorizons/CodeChickenCore
CodeChickenLib is no longer necessary
Controlling: https://github.com/GTNewHorizons/Controlling
CookingForBlockheads:  https://github.com/GTNewHorizons/CookingForBlockheads
EnderStorage: https://github.com/GTNewHorizons/EnderStorage
ExtraCells2: https://github.com/GTNewHorizons/ExtraCells2 but AE2FCR should probably be installed as well https://github.com/GTNewHorizons/AE2FluidCraft-Rework
Forbidden Magic: https://github.com/GTNewHorizons/ForbiddenMagic
Forge Multipart: https://github.com/GTNewHorizons/ForgeMultipart
GTNHLib: https://github.com/GTNewHorizons/GTNHLib
HelpFixer: https://github.com/GTNewHorizons/HelpFixer
Hodgepodge: https://github.com/GTNewHorizons/Hodgepodge recommend using stable non-pre
Iguana Tinker: Tweaks https://github.com/GTNewHorizons/IguanaTweaksTConstruct
INpureCore: https://github.com/GTNewHorizons/INpureCore
inventory tweaks: https://github.com/GTNewHorizons/inventory-tweaks
JABBA: https://github.com/GTNewHorizons/jabba
LunatriusCore: https://github.com/GTNewHorizons/LunatriusCore
Mantle: https://github.com/GTNewHorizons/Mantle
MineTweaker3 -> CraftTweaker: https://github.com/GTNewHorizons/CraftTweaker
MobiusCore can be removed, we don't use Opis afaik
ModTweaker: https://github.com/GTNewHorizons/ModTweaker
MouseTweaks: https://github.com/GTNewHorizons/MouseTweaks
Natura: https://github.com/GTNewHorizons/Natura (I think I checked this for compatibility?)
NEI Addons: https://github.com/GTNewHorizons/neiaddons
NEI Plugins -> NEI-Integration: https://github.com/GTNewHorizons/NEI-Integration (NEI Plugins has [a single update](https://web.archive.org/web/20141024051918/http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294687-toniuss-mods-simply-jetpacks-fluxedfeederunit-nei) newer than what is in the pack but it doesn't add integration for any mods we use anyways)
NotEnoughItems: https://github.com/GTNewHorizons/NotEnoughItems
I don't think Player-API is used anywhere either. But GTNH has a fork of it if it does
Schematica: https://github.com/GTNewHorizons/Schematica
serializationisbad: https://github.com/dogboy21/serializationisbad
SpiceOfLife needs your PR merged before we can use the NH fork
StorageDrawers https://github.com/GTNewHorizons/StorageDrawers
TCInventoryScanning: https://github.com/GTNewHorizons/ThaumicInventoryScanning
TCNodeTracker: https://github.com/GTNewHorizons/TCNodeTracker
TC4Tweak: https://www.curseforge.com/minecraft/mc-mods/tc4tweaks
TCNEIAdditions: https://github.com/GTNewHorizons/TCNEIAdditions
ThaumicEnergistics: https://github.com/GTNewHorizons/ThaumicEnergistics
Might not want to use the NH fork of ThaumicTinkerer, at least until I'm remotely bothered to upstream the changes.
TiC Tooltips: https://github.com/GTNewHorizons/TiC-Tooltips
Tinkers Mechworks: https://github.com/GTNewHorizons/TinkersMechworks
Tinkers' Construct: https://github.com/GTNewHorizons/TinkersConstruct
TooMuchLoot: https://github.com/GTNewHorizons/TooMuchLoot
Translocators: https://github.com/GTNewHorizons/Translocators
UniMixins: https://github.com/LegacyModdingMC/UniMixins
Waila: https://github.com/GTNewHorizons/waila
Waila Harvestability: https://github.com/GTNewHorizons/WailaHarvestability
This should be everything?

**Comment by LazyFleshWasTaken** [comment]
And Automagy

**Comment by JL2210** [comment]
Automagy doesn't have a GTNH fork as far as I can tell. It's also ARR.

I have to assume thaat if it's not already on the newest version there's probably a reason for it, like there is with Botania

**Comment by Midnight145** [comment]
Botania is being updated next patch to [this branch](https://github.com/Midnight145/Botania/tree/blightfall) which ports some old behavior into the latest GTNH release

**Comment by Midnight145** [comment]
> And Automagy

Automagy seems to be up to date, is there a newer version than the one on Curseforge?

**Comment by LazyFleshWasTaken** [comment]
> And Automagy

This was in response to the fire shard popping up and the fragments not being craftable, but that fixed itself in my instance later.

**Comment by Midnight145** [comment]
yeah that's a thaum issue that I don't really know how to fix

**Comment by JL2210** [comment]
I think that's everything. I haven't bothered updating or testing *any* of these links so don't expect everything to be peachy.
Some of these may or may not be up to date either. But most probably will need to be updated unless they're either not GTNH mods or we're already using a GTNH mod.

**Comment by Midnight145** [comment]
> > And Automagy
> 
> This was in response to the fire shard popping up and the fragments not being craftable, but that fixed itself in my instance later.

fixed in https://github.com/Midnight145/TCNEIAdditions/commit/31a92f7412217dab1d70c0eb47bd44fdcbca30b2
