### ISSUE TITLE
Totems of Dawn complete ineffective on eerie island

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [Midnight145/blightfall-issue-tracker#135]
Title. I've placed the totems on the island, and even after several minutes of work, not one patch of taint was cleared around either of the 4 of them. THe purity focus also does nothing to it.

I think that base biome is eerie is messing it up, since usually they would also turn eerie biome back into whatever it is beneath.

**Comment by LazyFleshWasTaken** [comment]
Above also applies to base biome magical forest.

**Comment by Midnight145** [comment]
Forgot to ask, is this in the public beta or official release?

**Comment by LazyFleshWasTaken** [comment]
3.1.2 Rc 1 with the config fix

**Comment by Midnight145** [comment]
alright, that makes more sense

**Comment by LazyFleshWasTaken** [comment]
I _believe_ it was the same on 3.1.1, but no one else seems to have a problem, so idk?

edit: checked, it works fine.
