### ISSUE TITLE
Can't make a hardcore world

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [Midnight145/blightfall-issue-tracker#136]
Title. This is in release candidate 1 for 3.1.2, so it may be fixed later. Nothign in the logs, the last updated one was me closing my previous world.

SC:
![image](https://github.com/user-attachments/assets/53a873d7-e3be-42db-b5a3-fee806d26068)

**Comment by LazyFleshWasTaken** [comment]
Persists after isntance restart

**Comment by LazyFleshWasTaken** [comment]
I was wrong, the log was in crash reports, not logs. Idk why it told me to look in logs.

[crash-2024-08-07_22.08.52-client.txt](https://github.com/user-attachments/files/16537974/crash-2024-08-07_22.08.52-client.txt)
[crash-2024-08-07_22.09.17-client.txt](https://github.com/user-attachments/files/16537976/crash-2024-08-07_22.09.17-client.txt)
[crash-2024-08-07_22.13.04-client.txt](https://github.com/user-attachments/files/16537977/crash-2024-08-07_22.13.04-client.txt)
[crash-2024-08-07_22.14.25-client.txt](https://github.com/user-attachments/files/16537978/crash-2024-08-07_22.14.25-client.txt)
[crash-2024-08-07_22.14.33-client.txt](https://github.com/user-attachments/files/16537979/crash-2024-08-07_22.14.33-client.txt)

**Comment by JL2210** [comment]
Vanilla hardcore isn't supported, try `/hqm enable`

**Comment by LazyFleshWasTaken** [comment]
> Vanilla hardcore isn't supported afaik, try `/hqm enable`
> 
> Probably shouldn't crash though.

Ye, def shouldn't crash. When I tried to do it in 3.1.1 it just didn't make a hardcore, or creative, world.

Did it by just editing nbt, wasn't too bad.

**Comment by Midnight145** [comment]
I can't reproduce the crash on my end

Not being able to make it hardcore is an unavoidable sideeffect of using Lockdown, I honestly might toggle the config to remove the button since it doesn't work anyway

**Comment by Midnight145** [comment]
button removed in https://github.com/Midnight145/blightfall-configs/commit/c68c37adf733fdf42d5d215041184af138dc64e5 as it was broken anyway
