### ISSUE TITLE
Remove Unifier block from Minefactory Reloaded

### ISSUE THREAD

**Issue by richardhendricks** [Midnight145/blightfall-issue-tracker#137]
The Unifier block oredict recipes to convert items have been disabled, but it is still mentioned as a frequent solution for converting slime colors.  Please remove the block if it no longer works, or at least update its tooltip to state that it is disabled.

**Comment by Midnight145** [comment]
There's been a few tweaks to specific unifier recipes due to balance changes, but the block as a whole works.

**Comment by richardhendricks** [comment]
I just tried to convert a Natura bloodwood stick to a normal stick and it didn't do anything.  Which recipes are working and which are not?  Could we get a quest to cover the allowed/disallowed operations?

**Comment by Midnight145** [comment]
<ore:woodStick> may be disabled because it would allow for unintended natura wood generation if I had to guess. I'll go through later and make a list of the disabled oredict entries, though some are also disabled because the unifier won't change anything that has multiple oredict entries.

**Comment by richardhendricks** [comment]
Thanks for the consideration.  My son was pretty upset when he couldn't use it to convert slime and had to build a mega slaughter house.

**Comment by Midnight145** [comment]
Here are all of the oredict entries explicitly disabled in the config file, though it's possible others are disabled in the MFR source code directly. Other items may have also had their oredictionary entries tweaked which might disallow it as well, I'm not entirely sure.
```
<ore:dyeBlue>
<ore:dyeWhite>
<ore:dyeBrown>
<ore:dyeBlack>
<ore:listAllwater>
<ore:listAllmilk>
<ore:resourceTaint>
<ore:shardNether>
<ore:slimeball>
<ore:magicSapling>
<ore:nuggetGold>
```
