### ISSUE TITLE
Mana bottle / mana cookie recipes need to be disabled if impossible to do

### ISSUE THREAD

**Issue by richardhendricks** [Midnight145/blightfall-issue-tracker#138]
Since there is no source of mana beans, we can't make mana cookie dough for mana cookies.  I assume this is on purpose since they are immune to diminishing returns.

Recommend removing the mana bottle recipe completely since it isn't used in any other recipes.

Or if we are intended to get mana cookies, add in a way to get mana beans/grow them.

**Comment by tiflu** [comment]
mana beans spawn naturally in the magical forest

**Comment by Midnight145** [comment]
Mana beans can be found in the silverwood grove if I remember correctly. There's not a ton of them, but enough to start growing your own.

They are intentionally free from diminishing returns are they are expensive and difficult to make, being one of the fairly few ways to "cheese" the hunger system.

**Comment by richardhendricks** [comment]
hmm will recheck.  The area has been pretty tainted out though.

**Comment by Midnight145** [comment]
Some should be protected by the pure nodes on silverwood trees

**Comment by Midnight145** [comment]
Should be some at 937, 72, 1790 protected by a pure node

**Comment by richardhendricks** [comment]
Ah ty ty I did some better exploring now that the normal forest has been removed by a totem and see several.  Just need to make an axe before I accidentally use a lumberaxe! :D

**Comment by richardhendricks** [comment]
Thanks for keeping this awesome modpack alive btw

**Comment by Midnight145** [comment]
No problem, glad to do it!

**Comment by yui-hime** [comment]
I have signed up for GitHub purely to remind all y'all that pechs exist! And they can trade you beans.

IIRC, they require a non-taint magical biome (eerie, magical forest) and low-light conditions to spawn, and you trade by throwing Lucrum-aspect objects at them and seeing what they throw back.

**Comment by Midnight145** [comment]
Oh, true, I always forget about pechs, thank you!

**Comment by rndmorris** [comment]
You can also purchase mana beans from one of Thaumcraft's villager types.
