### ISSUE TITLE
Learning to Scout waypoint keybind shows B when default was changed to N

### ISSUE THREAD

**Issue by Midnight145** [Midnight145/blightfall-issue-tracker#14]
![image](https://user-images.githubusercontent.com/23142346/216724358-60f0642c-f0ec-4583-b43b-1a2a2920ca50.png)

**Comment by Midnight145** [comment]
weird, default is still B for most

**Comment by tiflu** [comment]
> weird, default is still B for most

default is N. it seems that some keybinds were kept when updating. hitting "reset to default" changes it to N.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/9d6fbdadb2ee26f8ee29567257d4a4b82453c5fe), will be fixed next release
