### ISSUE TITLE
Manasteel pickaxe is Supra-Diamond, Manasteel pickaxe head is just Diamond

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [Midnight145/blightfall-issue-tracker#140]
Blightfall Version: 3.1.2 RC 1

**Describe the bug**
Manasteel pickaxe is Supra-Diamond, Manasteel pickaxe head is just Diamond

**To Reproduce**
Look in nei

**Expected behavior**
I expect the two mining levels to be the same. 

**Screenshots**
![image](https://github.com/user-attachments/assets/d4a9595e-83be-4a6e-a827-bd0dff550aa3)
![image](https://github.com/user-attachments/assets/9a371f0c-79e9-46ef-bf09-22907a409f63)

**Additional context**
Since both Terrasteel and Elementium are supra-diamond as pickaxe heads, even though they are much better materials, I think botania metals just need a general look-over.

**Comment by Midnight145** [comment]
Manasteel has been adjusted to Diamond mining level, terrasteel has been adjusted to Alien, elementium has stayed at supra-diamond

**Comment by LazyFleshWasTaken** [comment]
Elementium is after terrasteeel tho

**Comment by Midnight145** [comment]
It's easier to get more of though, with it only requiring two iron and a little bit of mana, vs terrasteel's iron, diamond, pearls, and half a pool of mana.

**Comment by Midnight145** [comment]
You'll find similar behavior in base botania as well, with all of the actual endgame items being terrasteel instead of elementium
