### ISSUE TITLE
Autonomous activator Black hole Talisman crash [bug]

### ISSUE THREAD

**Issue by skythegguy** [Midnight145/blightfall-issue-tracker#141]
Blightfall Version: 3.1.1(CE)

**Describe the bug**
When putting a Botania black hole talisman that contains blocks into an autonomous activator to continually place blocks, the game will crash shortly after it runs out of blocks to place.

**To Reproduce**
1: Place a black hole talisman containing blocks into autonomous activator
2: wait for activator to consume all blocks in the talisman (some other visual bugs will also occur here)
3: once the last item is consumed by the talisman, the game should promptly crash. world will crash every time world is entered unless activator or talisman is removed. (didn't test if it was possible to remove items/block in this state)

**Expected behavior**
Activator shouldn't be able to do much of note, maybe switch the talisman's held block to air or something.

**additional note**
I think the black hole talisman was active (accepting items) and didn't think to test if there was any difference with an inactive talisman but I don't think there were. Other bugs surrounding this whole thing included: seeming to consume blocks even when block in front of it is occupied, and (visual) forcing the black hole talisman item display to always be active while in the activator.

**Comment by Midnight145** [comment]
Can you upload the crashlog?

**Comment by skythegguy** [comment]
Appologies for the wait, shut my PC down for the night shortly after posting. Also a correction to previous statement, it happens when the activator tries to right click air, doesn't crash if there is still a block in front of it.

[crash-2024-08-18_11.54.36-server.txt](https://github.com/user-attachments/files/16649873/crash-2024-08-18_11.54.36-server.txt)

**Comment by Midnight145** [comment]
Doesn't seem to crash in (what will be) next patch, so closing for now
