### ISSUE TITLE
[bug] Alumite Mislabeled as Alien Mining Level Material

### ISSUE THREAD

**Issue by BillyBobJoe12345** [Midnight145/blightfall-issue-tracker#145]
Blightfall Version: 3.1.1-CE

Mining and Resource Collection (Book 1) claims Alumite is Mining Level Alien, but NEI/Tinkers says it is Supra-Diamond

Open Book 1/Mining and Resource Collection without having unlocked an alien level material
The book will detect alumite as Supra-Diamond, but the book claims it is Alien

The book should either have Alumite written in the Supra-Diamond Material Section and it being removed from the Alien Hardness list or only removed from the Alien Hardness list

Fresh Book without grabbing any material
![image](https://github.com/user-attachments/assets/c1bab927-f91f-4629-aaa1-605e511b8bb4)

Book after grabbing alumite ingot
![image](https://github.com/user-attachments/assets/e8d71bcc-d520-4fdc-93d7-b7a5dbe08f60)

Alumite Pickaxe Head
![image](https://github.com/user-attachments/assets/25d352d6-b4ef-4f3b-bf08-b8337f77e04c)

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/CavesToKingdoms/commit/c218965acb525ce0c173d60e308208d39263f33e)
