### ISSUE TITLE
Make vishrooms and cinderpearls obtainable with/without dawn machine

### ISSUE THREAD

**Issue by JL2210** [Midnight145/blightfall-issue-tracker#147]
**Is your feature request related to a problem? Please describe.**
Can't get vishrooms at all, can't get cinderpearls before dawn machine

**Describe the solution you'd like**
A way to obtain both without the dawn machine.
Also planting vishrooms in the magical forest with the dawn machine

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by BillyBobJoe12345** [comment]
My idea for this would be the petal apothecary, i.e. similar to the botanist's shimmerleaf

**Comment by Midnight145** [comment]
added in https://github.com/Midnight145/BlightTweaks/commit/b3a0c53bf6a770e858f0c5eac2c997eb77503694
