### ISSUE TITLE
Resonant Ender produces Liquified Ender

### ISSUE THREAD

**Issue by ChargeRunner** [Midnight145/blightfall-issue-tracker#15]
When picked up as a tile block from the world, resonant ender turns into liquified ender. This has no effect on placing the material (returns to resonant), and it can still be used in a smeltery, but the enderium crafting recipe requires a resonant ender bucket, not a liquified ender, making the bucket unusable in that particular case.

**Comment by Midnight145** [comment]
will be fixed in next release

if you want to go ahead and fix, add this line to scripts/Misc. Singletons.zs

`recipes.addShapeless(<ThermalFoundation:material:44> * 4, [<ore:dustTin>, <ore:dustTin>, <ore:dustSilver>, <ore:dustPlatinum>, <TConstruct:buckets:23>]);`

**Comment by Midnight145** [comment]
apparently this never got pushed to release, reopening so I don't forget about it
