### ISSUE TITLE
The sleeping quarters in the jaded are made of 2 different marbles, one of which is canonically only on this planet

### ISSUE THREAD

**Issue by BillyBobJoe12345** [Midnight145/blightfall-issue-tracker#150]
The sleeping quarters in the jaded are made of 2 different marbles, one of which is canonically only on this planet
The stairs and the slabs are 2 different marbles
probably should change that

**Comment by Midnight145** [comment]
using UBC marble is intentional as chisel slabs can't be placed on the top half of blocks
