### ISSUE TITLE
[bug] Induction smelter can't run the Nether shard recipe with maxed out speed augments.

### ISSUE THREAD

**Issue by skythegguy** [Midnight145/blightfall-issue-tracker#152]
Blightfall Version: 3.1.1-CE

**Describe the bug**
Due to the energy requirements of the Nether shard recipe for the induction smelter (50,000RF) and the size of the internal buffer of the induction smelter (120,000 RF) when the cost is increased by the third speed upgrade (+150% or 2.5x) it exceeds the internal buffer size of the induction smelter and does not run, regardless of your ability to supply the induction smelter's 800rf/tick consumption.

**To Reproduce**
using a resonant induction smelter, insert all three speed augments. fill it with energy. 
attempt to run the recipe for a nether shard (4 fire shards, 1 wrath shard)
It will not run until the tier 3 speed augment is removed.

**Expected behavior**
Induction smelter should ideally run so long as you're able to supply its 800rf/tick consumption, and not be bounded by its internal capacity.

**Screenshots**
![image](https://github.com/user-attachments/assets/b2cf1196-642d-498c-a675-38e737f2ce09)
![image](https://github.com/user-attachments/assets/985c1d27-d5e4-4f6d-ab57-268c21138f76)

**Additional context**
I believe the simple fix would be to lower the recipe's energy requirement to something like 45,000RF which is still large but remains under the 120,000RF. 48000rf would perfectly hit the internal buffer cap, uncertain if it would run or not at that value.

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightfall-configs/commit/c68c37adf733fdf42d5d215041184af138dc64e5
