### ISSUE TITLE
[bug] Casts can no longer be made out of gold

### ISSUE THREAD

**Issue by Midnight145** [Midnight145/blightfall-issue-tracker#153]
Blightfall Version: 3.2.0-beta4

**Describe the bug**
Casts can only be made out of aluminum brass

**To Reproduce**
n/a

**Expected behavior**
should be gold recipes as well

**Screenshots**
n/a

**Additional context**
n/a

**Comment by JL2210** [comment]
Config option (`TinkersConstruct.cfg`):
```
"difficulty changes" {
    ...
    B:"Remove Gold Cast Recipes"=true
    ...
}
```
As to why this is enabled by default I don't know

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightfall-configs/commit/b5b0b9def5117c9b34ce9131894c4c2b05ba8ad9
