### ISSUE TITLE
[bug]: Salt Ore not picked up by Ritual of Magnetism

### ISSUE THREAD

**Issue by KyokoDolls** [Midnight145/blightfall-issue-tracker#154]
Blightfall Version: 3.2.0

**Describe the bug**
Salt ore is not picked up by the Ritual of Magnetism

**To Reproduce**
Preform the Ritual of Magnetism with salt ore within its range (usually below it)

**Expected behavior**
The ritual should pull the salt ore up like every other ore

**Screenshots**
n/a

**Additional context**
n/a

**Comment by Midnight145** [comment]
fixed by https://github.com/Midnight145/blightfall-configs/commit/56f7ccc61838037b5b30c6833344bc108144fd6a
