### ISSUE TITLE
Purity focus takes much longer and is much more expensive

### ISSUE THREAD

**Issue by tiflu** [Midnight145/blightfall-issue-tracker#155]
Blightfall Version: 3.2.0-beta4, 3.1.2-RC1

**Describe the bug**
Purity focus is much slower and more expensive than it is in the stable release (3.1.1-CE). Before, it cleaned a whole column instantly, costing no more than 1 vis per column. Now, it purifies much slower, working from y=0 up.

**To Reproduce**
Use a purity focus on the beta. Effect is more noticeable on a vertical face, such as the side of a ravine.

**Expected behavior**
The whole column is cleaned instantly regardless of height or amount of taint.

**Screenshots**
Here's a good (extreme) example of the amount of time it takes, along with the vis cost (about half of a silverwood wand's capacity with a base focus):
https://github.com/user-attachments/assets/d345c426-d541-421c-9c55-a7718eccbd2c

Here's one that shows the effect of it working up from the bottom:
https://github.com/user-attachments/assets/961ed207-7f58-467b-a410-58b99c13154c

For reference, here's the same experiment repeated on 3.1.1:
https://github.com/user-attachments/assets/0d799c49-3910-4b83-9195-d69a80a0c80b

**Comment by Midnight145** [comment]
fixed in https://github.com/Midnight145/blightbuster/commit/c1bdd3c9617bbb132f4bdbeaf8749e4c124957ff
