### ISSUE TITLE
Add aspects to Tainted Blood Shard

### ISSUE THREAD

**Issue by Balor64** [Midnight145/blightfall-issue-tracker#160]
Tainted Blood Shards are currently completely useless in single player, and in cooperative multiplayer too. It has no uses outside of pvp, and even there it isn't very good. They also drop pretty commonly, which is annoying when they're so useless.

It would be nice if we could melt them down into essentia, so we could at least get some use out of them. Perhaps 2 Victus and 2 Vitium? Maybe a Vitreus too.

**Comment by rndmorris** [comment]
I would suggest Spiritus instead of Victus, since they're shards of a mob's soul network.
