### ISSUE TITLE
putting a TC item in a blood altar crashes the world

### ISSUE THREAD

**Issue by MrVelcro** [Midnight145/blightfall-issue-tracker#17]
world exits out and a relaunch is needed.

**Comment by Midnight145** [comment]
Can you send a logfile?

**Comment by MrVelcro** [comment]
where do I find those?

**Comment by Midnight145** [comment]
technic launcher --> modpack options --> open folder --> logs/latest.log

**Comment by MrVelcro** [comment]
[2023-02-04-1.log.gz](https://github.com/Midnight145/blightfall-issue-tracker/files/10609390/2023-02-04-1.log.gz)

**Comment by MrVelcro** [comment]
also, it specifically happened with an iron bow (one of the ones that drops from custom NPCs) and the altars blood level decreased then quickly went back to normal, in case that helps

**Comment by Midnight145** [comment]
will look into making a new blood magic build to fix this once i have my new laptop--might not be fixed in next release, but will be fixed

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/BloodMagic/commit/c2bdf994fc1618376401b664808a3972d168bdcc), will be fixed in next release.
