### ISSUE TITLE
"A New Dawn" quest doesn't recognize the dusk/dawn ritual diviner or the regular one

### ISSUE THREAD

**Issue by MrVelcro** [Midnight145/blightfall-issue-tracker#18]
Even while set to the ritual of the new dawn, the diviner is not recognized by the questbook. May have something to do with the fact that while set to a ritual, the item is named ritual:[ritual name] instead of ritual diviner, but that doesn't change the items ID so maybe not
![image](https://user-images.githubusercontent.com/58572555/216784744-f42a6bd6-3147-41b2-945d-6a3dbfea8539.png)

![image](https://user-images.githubusercontent.com/58572555/216784764-fc47fe53-53a6-46e1-a591-9c3dc539753b.png)

**Comment by Midnight145** [comment]
I'll look into it--it's possible that I need to change the detection to be fuzzy not exact, though I thought I did that already, but possibly not. Try it with a "new" ritual diviner if you can, one not bound to anyone and see if that fixes it.

**Comment by MrVelcro** [comment]
a cheated in dawn/dusk diviner with no owner didn't work, nor did any other type of diviner created through that method

**Comment by Midnight145** [comment]
Hmm, alright. Will double check the quest to see what exactly it's looking for.

**Comment by Midnight145** [comment]
Ahh, yep--reproduced, and will be fixed in the next release. For now, you can either `/hqm edit` and force-complete the quest, or change config/hqm/editmode.cfg to edit the item detection to ignore nbt data.
