### ISSUE TITLE
Missing Crafting Recipe for Greatwood Slabs

### ISSUE THREAD

**Issue by CallandorG** [Midnight145/blightfall-issue-tracker#19]
Attempting to craft greatwood slabs instead results in oak wood slabs.

**Comment by tiflu** [comment]
Silverwood has the same issue. may be worth checking for other wood types.

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/bf7799ea3bcedae1ae5218a1d0a735bea1d49941), will be in next release
