### ISSUE TITLE
the game crashes when the quest book is opened

### ISSUE THREAD

**Issue by MeguSwagg** [Midnight145/blightfall-issue-tracker#20]
Hello everyone,
With friends we are playing on a silly aternos server but whenever someone try to open the questbook, his client crashes. The versions of the client and the server are 3.0.1. 
Any idea?
thx

**Comment by tiflu** [comment]
Sounds like it might be not actually 3.0.1
here's a fix from midnight from before 3.0.1 came out, i dunno how much you can access on aternos, but here you go: "server pack is broken, copy over config/hqm/quests.hqm from the client to config/hqm/quests.hqm to the server"

**Comment by MeguSwagg** [comment]
thank you, this was the issue

**Comment by Midnight145** [comment]
Aternos servers have been fixed. Make sure you do have the quest file from 3.0.1 now, as aternos servers now have the file from 3.0.1.
