### ISSUE TITLE
Angmallen Smeltery Dupe

### ISSUE THREAD

**Issue by Nouonn** [Midnight145/blightfall-issue-tracker#21]
https://youtu.be/Wd3XCjyLrCI

I somehow deactivated the glitch but was able to reactivate it again

Have som fun with this :)

**Comment by Midnight145** [comment]
Video is private, can you set it to unlisted?

**Comment by Midnight145** [comment]
Currently closing as I'm unable to reproduce, but if you find a consistent setup for it feel free to reopen.
