### ISSUE TITLE
Diamond Modifier Description (Tools and Modifiers Book)

### ISSUE THREAD

**Issue by Nouonn** [Midnight145/blightfall-issue-tracker#23]
![grafik](https://user-images.githubusercontent.com/116109974/217055011-f8ce7b44-0de5-4ca8-b57b-ce83a315ec0c.png)
![grafik](https://user-images.githubusercontent.com/116109974/217055064-9cc40d4b-f366-4ca4-a2fa-12c753d56817.png)
Tools and Modifiers book says diamond modifier doesnt effect mining level, however it does (to Hard-Metal).

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/blightbuster/commit/edb3133e90a72d90fc25efd784810b858d0cc6f7), will be in next release
