### ISSUE TITLE
Black Market Mithril Incompatibility

### ISSUE THREAD

**Issue by tiflu** [Midnight145/blightfall-issue-tracker#24]
The Black Market mithril quests require mithril blocks from metallurgy, but the smeltery outputs the thermal version. Difficult or impossible to convert the thermal version back to metallurgy.

**Comment by Midnight145** [comment]
Quest accepts oredict entries to currently mithril block works, clarification text was added in [this commit](https://github.com/Midnight145/blightfall-configs/commit/48f295553079b71ea97e9ee024ea9a2c403aff6c)
![image](https://user-images.githubusercontent.com/23142346/217415069-bfbe85f9-7061-4c70-904d-4744d41c7aca.png)
