### ISSUE TITLE
Natura seeds cannot be used to make seed soup

### ISSUE THREAD

**Issue by MrBenjaminBowman** [Midnight145/blightfall-issue-tracker#26]
Barley and Cotton seeds cannot be used to make seed soup:
![image](https://user-images.githubusercontent.com/40965491/217426074-8fd9b2bd-4d44-487c-9a7b-205840f68d8d.png)
![image](https://user-images.githubusercontent.com/40965491/217426127-144fc6df-2ed0-4655-a471-338f718bdd18.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/40965491/217426151-58dba237-9ef5-405c-8c68-f4b4a8b9c305.png)

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/4247d7edb553a25487013ec011d19dca32241c01), will be pushed in next release
