### ISSUE TITLE
Incorrect Crafting

### ISSUE THREAD

**Issue by LeonMercury** [Midnight145/blightfall-issue-tracker#28]
Crafting stained glass panes with Minefactory Reloaded stained glass produces the minecraft stained glass panes, which don't work with the laser focus recipe.
![Screenshot 2023-02-08 173856](https://user-images.githubusercontent.com/124848065/217693074-5dd3cd45-e7cc-4192-aba7-1b1ece4c60fe.png)
![image](https://user-images.githubusercontent.com/124848065/217693136-6933896f-6b96-41c5-83f3-b72b799c359d.png)

**Comment by Midnight145** [comment]
Will be fixed next patch, mfr glass will properly class mfr glass panes
