### ISSUE TITLE
Spoiler: Advanced Node Jarring logs do not match texture+explanation

### ISSUE THREAD

**Issue by Jaari** [Midnight145/blightfall-issue-tracker#3]
See screenshot. Explanation + Texture says Silverwood logs, hovering over it says Greatwood logs.

![2023-02-02_21 33 47](https://user-images.githubusercontent.com/10313979/216444574-8f05e4f3-a34c-4f94-a005-83314a4389dd.png)

**Comment by MrBenjaminBowman** [comment]
This seems similar to how Waila shows sideways silverwood logs as greatwood logs as well:
![image](https://user-images.githubusercontent.com/40965491/216500228-72a8e3e3-bb14-4f61-b2d7-4bd2d3dad7ef.png)
It's probably just a thaumcraft issue

**Comment by Midnight145** [comment]
I _believe_ it's a thaum issue due to a block placed with a different rotation (like the Waila example) having a different damage value.

I'll think on it, but I can't think of any easy way to fix this right now.

**Comment by Midnight145** [comment]
I'll come back to this if I ever come up with an idea on how to fix it, but I currently don't have any
