### ISSUE TITLE
Bloodwood no longer usable as special material

### ISSUE THREAD

**Issue by MarineRusher** [Midnight145/blightfall-issue-tracker#31]
Tools made out of bloodwood now make regular wooden tools, and tools that were made out of bloodwood prior to update are now only repairable through the thaumic restorer/livingmoss or other non-material input ways to repair tools

**Comment by Midnight145** [comment]
huh, I really thought I would've caught this. I'll fix this and put out a patch real quick. I assume the other nether woods are the same way?

**Comment by MarineRusher** [comment]
Yes they are the same, just checked

**Comment by Midnight145** [comment]
Alright, thank you. Not entirely sure what caused this, but I'll get on this ASAP.

**Comment by Midnight145** [comment]
Root cause has been identified, working on a fix.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/9489681cbabfa1ed85447656616fe492d2b6eaf1), working on putting out a hotfix update
