### ISSUE TITLE
Artaxerxes spawning multiple times when visiting Iceberg

### ISSUE THREAD

**Issue by Jruskey** [Midnight145/blightfall-issue-tracker#32]
Title; when teleporting to the Iceberg, the sword underneath the Iceberg lab duplicates itself and drops on the floor, causing FPS drops.

**Comment by Midnight145** [comment]
I'm not sure what you mean, it works as expected on my end.
Can you provide a logfile and whether or not you're playing on a server?

**Comment by Jruskey** [comment]
I am playing a single player world, started in 3.0.1. Could you let me know where the specific log files you need are?

Also, I've taken a screenshot of the bug:
![2023-02-15_20 10 04](https://user-images.githubusercontent.com/29508852/219234406-dddf1741-7cfe-49b9-8be0-b01da10d8c1e.png)

**Comment by Midnight145** [comment]
how the fu-

**Comment by Midnight145** [comment]
Strange, I can't seem to reproduce this on my end.

**Comment by Jruskey** [comment]
Unfortunately I don't know where the logs are, so I can't give you any more information

**Comment by Midnight145** [comment]
Logs likely won't be helpful now that I think about it, as I don't have any logging statements in the code. Did it only happen on that one world, or is it reproducible on others?

**Comment by Jruskey** [comment]
Here's an image from a new world I created in creative mode:
![2023-02-16_17 32 02](https://user-images.githubusercontent.com/29508852/219502071-7f5f2d8a-ed43-4dd6-a3c0-44fb0bbaf205.png)

**Comment by Midnight145** [comment]
That's super strange. Later tonight I'll send a new version of blightfall-filefix, can you see if that fixes it?

**Comment by Jruskey** [comment]
Sure.

**Comment by Midnight145** [comment]
Sorry for the delay on this, took a bit longer than expected. Have to upload as zip because github won't let me upload the jar directly

[filefix.zip](https://github.com/Midnight145/blightfall-issue-tracker/files/10762811/filefix.zip)

**Comment by Jruskey** [comment]
It looks like the fix works!

Picture of the pristine minecart chest:
![2023-02-16_22 05 57](https://user-images.githubusercontent.com/29508852/219539538-27790cc9-27ba-415c-bc0e-376d6dc36982.png)

I'll close the issue since the fix will probably come with the next update. Thanks!

**Comment by Midnight145** [comment]
Thank you!! Gonna verify with one other person that reported the bug, and please reopen if the issue reoccurs, but otherwise closed.
