### ISSUE TITLE
Natura cotton cannot be used for anything

### ISSUE THREAD

**Issue by malaclypse2** [Midnight145/blightfall-issue-tracker#33]
Natura cotton cannot be crafted into string, wool, or the Pam's version of cotton. It can only be crafted back into Natura cotton seeds.

**Comment by Midnight145** [comment]
Will be fixed next patch. I accidentally broke some predict entries with the rushed natura patch to fix crafting, a more refined patch will be coming out soon to fix all of the crafting/oredict issues.
