### ISSUE TITLE
Vanilla sticks can only be made with oak planks

### ISSUE THREAD

**Issue by malaclypse2** [Midnight145/blightfall-issue-tracker#34]
You cannot create sticks with jungle planks, or any of the other vanilla (or modded) wood types. Natura woods make their own type of sticks, so those make sense. I think we should be able to make sticks from all the vanilla wood planks, plus probably the Thaumcraft planks as well.

**Comment by Midnight145** [comment]
Yeah, some changes I made to configs apparently screwed up all vanilla wood recipes. I didn't realize this until just a little bit ago, but I will work on it

**Comment by Midnight145** [comment]
will be fixed next patch
