### ISSUE TITLE
Occasional "X-ray" vision

### ISSUE THREAD

**Issue by KatrinkaRose** [Midnight145/blightfall-issue-tracker#35]
I haven't found a consistent pattern that triggers it but it occurs with increasing frequency the longer I'm in the game.  This time I was underground and things were rendering fine but when I went to the surface this is what I saw.  It is Not chunk based rendering issues, I can see tunnels directly under me when this happens.  Sometimes it goes away in moments other times the world doesn't actually render in until I reload the game.

![image](https://user-images.githubusercontent.com/90729629/219260991-09400c98-deb2-42a3-a5e1-96ed951aa822.png)

My computer is:
Intel i3-8100 @3.6GHz
16GB RAM
Radeon RX 560

**Comment by KatrinkaRose** [comment]
Another shot more straight down 
![image](https://user-images.githubusercontent.com/90729629/219263578-5109f433-555f-406b-a25b-6f4b45761d3a.png)

**Comment by Midnight145** [comment]
Did this happen pre-update? If not, try changing the line `cleanuptime=0` in config/chickenchunks.cfg to `cleanuptime=1200`

**Comment by KatrinkaRose** [comment]
It happened both on 3.0.1 and 3.0.4.  I'll test those config changes tomorrow.

**Comment by Midnight145** [comment]
Are you using optifine? If so, see if the bug persists without it

**Comment by KatrinkaRose** [comment]
The pack is 100% as downloaded.  No additions at all or config changes (other than the one you suggested above).  It hasn't happened yet today which was spent exclusively at my base.  Next I'll do some traveling around and see if that triggers it.

**Comment by KatrinkaRose** [comment]
Upon returning home after travel I put stuff away, placed a few blocks, and then crashed trying to open the Thaunomicon.  The log has "Warning: Clientside chunk ticking took 262 ms" just before I warped home (trackable as it reported that just before the new Transport location discovery). But still no visual rendering issues.

[Crashed on return to home.log](https://github.com/Midnight145/blightfall-issue-tracker/files/10762882/Crashed.on.return.to.home.log)

**Comment by Midnight145** [comment]
Where's your base?

**Comment by KatrinkaRose** [comment]
Alpha site.  Started fresh with the 3.0.4 update so it's still early progress.

**Comment by KatrinkaRose** [comment]
There we go, it's doing it again.  It does seem to be triggered by travelling.

**Comment by KatrinkaRose** [comment]
As I stand still and watch the world around me I can see bits fairly rapidly popping in and out.  Absolutely nothing in the log when it started, though now after a few minutes watching and screenshotting this it's popped up the clientside chunk ticking 354ms again.

![image](https://user-images.githubusercontent.com/90729629/219555567-3faca701-4097-493f-9539-5e1ffe2460aa.png)
![image](https://user-images.githubusercontent.com/90729629/219555615-db09a476-1d24-4ab8-a058-daff1cfed6c6.png)
![image](https://user-images.githubusercontent.com/90729629/219555661-f8534be8-bcaf-4648-b5e2-7fe4b2a7a976.png)

**Comment by KatrinkaRose** [comment]
And if I leave it doing the oddness long enough it eventually goes to: 
![image](https://user-images.githubusercontent.com/90729629/219556629-6d464627-84d2-4b39-9582-8fad0ae59cf0.png)

**Comment by KatrinkaRose** [comment]
Note: when this is happening I can move normally and interact with things.  Even with the snow the game sounds still play and the game closes out gracefully with no errors logged.

**Comment by KatrinkaRose** [comment]
I just triple checked: video card drivers are up to date.

**Comment by KatrinkaRose** [comment]
This may have nothing to do with the pack.  All three computers in the house running AMD cards have had odd graphics related issues in various games since the latest windows update.  The only computer that hasn't had any unusual glitches is the one with an NVIDIA card.

**Comment by Midnight145** [comment]
Yeah, there's nothing in the update that would've caused anything like that. It's likely some kind of Windows or driver issue if all three AMD cards have been having various graphical errors.

If it's alright with you, for now I'm going to close this until/if we get further information for whether this is related to Blightfall specifically

**Comment by KatrinkaRose** [comment]
That's fine.  I'll continue to watch for my own sake and see if I can pinpoint it to something you may be able to do something about but for now it looks like it isn't pack specific.

**Comment by Midnight145** [comment]
Alright. Feel free to reach out to me on Discord or reopen the issue if you find anything else.
