### ISSUE TITLE
accidental double drops using Tcon(/normal?) pickaxe

### ISSUE THREAD

**Issue by Brettman130** [Midnight145/blightfall-issue-tracker#36]
Sometimes while mining ores (iron, prom, nether ores, etc.) I get double the ores while using a regular pickaxe (no luck/lapis). Pretty nice but not the way the pack is supposed to work. 

Haven't tried this out using the copper pickaxe or smtn but it's happened a couple of times now.

**Comment by Midnight145** [comment]
I haven't been able to reproduce, feel free to reopen if you find a consistent way to
