### ISSUE TITLE
TiCon Chisels not behaving.  They're not supposed to be food, right?

### ISSUE THREAD

**Issue by kagenin** [Midnight145/blightfall-issue-tracker#39]
I made a Tinkers Construct chisel but right clicking with it in my hand just seems to make me gnaw on it?  Nothing happens, either.  Bloodwood parts, if it matters.

Tangentially, I made a hole in my glass dome, and wanted to patch it up with what looks to be the bubble glass that the rest of the dome is, but I'm having a hard time figuring out how to get the bubble glass variant.

Many thanks for making and updating the pack, BTW.  Really enjoying the progression.

**Comment by Midnight145** [comment]
The chisel from the chisel mod is what has the GUI when you right-click with it, I'm not sure what all ticon chisels are supposed to do

**Comment by Midnight145** [comment]
sounds like this is expected behavior, closing
