### ISSUE TITLE
Crash to menu when viewing recipe for crystal scribing tools

### ISSUE THREAD

**Issue by Jaari** [Midnight145/blightfall-issue-tracker#4]
Only applicable for NEI recipe viewing of the Forbidden Magic crystal scribing tools. Thanks for Coretweaks for not CTD'ing me.

https://gist.github.com/Jaari/410fde442a0d5b28af69ed55435d5f33

**Comment by tiflu** [comment]
Reproduced same issue by cheating in all research and clicking on crystal scribing tools in NEI. CoreTweaks caught the exception: net.minecraft.util.ReportedException: Rendering item in class net.minecraft.client.renderer.EntityRenderer

**Comment by Midnight145** [comment]
reproduced, will start looking into it

**Comment by Midnight145** [comment]
figured it out--it's a bug in thaumcraft, will look into trying to fix it in other ways, but i may have to make five static recipes, one recipe for each shard type

it's days like these where i wish thaum was open source

**Comment by Midnight145** [comment]
The newest version of GTNH NEI avoids a crash but still doesn't render properly, which is likely as good as we're going to get for now, as modtweaker isn't letting me change the recipe. I've opened an [issue](https://github.com/GTNewHorizons/NotEnoughItems/issues/350) on GTNH's github to see if they can do anything, but I'm closing this for now

**Comment by Midnight145** [comment]
Apparently this is a Forbidden Magic issue which was resolved in https://github.com/GTNewHorizons/ForbiddenMagic/commit/9dd71a2911000ad278f39a6d8da468a4ec2493dc, so this will be fixed next patch assuming no compat issues with the new version are found.

**Comment by Midnight145** [comment]
actually fixed in https://github.com/Midnight145/TCNEIAdditions/commit/31a92f7412217dab1d70c0eb47bd44fdcbca30b2
