### ISSUE TITLE
No recipe for Oak Wood Slabs

### ISSUE THREAD

**Issue by malaclypse2** [Midnight145/blightfall-issue-tracker#42]
Oak Wood Planks cannot be made into Oak Wood Slabs. The other Vanilla, Thaumcraft, and Natura slabs all seem okay.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/6d6cc8a1c7ca2411834573f8d509e84748f548bf)
