### ISSUE TITLE
double/no recipe for certain outputs (see files)

### ISSUE THREAD

**Issue by Brettman130** [Midnight145/blightfall-issue-tracker#43]
[
![2023-02-23_21 39 06](https://user-images.githubusercontent.com/125604761/221025343-98f4ada8-3a98-421e-bd7f-f080b4c15760.png)
![2023-02-23_21 39 09](https://user-images.githubusercontent.com/125604761/221025373-5ac41d27-549b-4022-87d3-934cbf04989d.png)

**Comment by Midnight145** [comment]
Check if you have two files named very similar things, and if you do, delete one of them
