### ISSUE TITLE
Bound Armor quest doesn't detect bound armor

### ISSUE THREAD

**Issue by Deiwos** [Midnight145/blightfall-issue-tracker#45]
Hitting Manual Detect doesn't do anything. Presumably because the quest is expecting the base items, rather than pieces with stuff slotted in them as you would actually make.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/f245118d3ff6541e99cdaeba3139491703d40f9c)
