### ISSUE TITLE
Blood Magic Convocation of the damned structures generate incorrectly

### ISSUE THREAD

**Issue by DWiz24** [Midnight145/blightfall-issue-tracker#46]
When you open the demon portal, all the houses are basic with no chests and a "schematic saver" block with invalid texture in the middle. This was fixed for me by deleting the config/BloodMagic/schematics folder. It regenerates the correct schematics automatically. See [this issue on the BM github](https://github.com/WayofTime/BloodMagic/issues/870)

**Comment by Midnight145** [comment]
will be fixed next release, folder deleted in [this commit](https://github.com/Midnight145/blightfall-configs/commit/4cf3494861851ab923f9c7e56a524edc35932f6f)
