### ISSUE TITLE
Thermal Foundation Tin and Copper ore cannot be smelted by vanilla furnace

### ISSUE THREAD

**Issue by VeryPeeved** [Midnight145/blightfall-issue-tracker#47]
They can only be smelted by a Redstone Furnace, or melted in a Smeltery (or processed in other ways, of course, like pulverizing).

Meanwhile, the Tinkers' Construct versions of the ore in NEI apparently can't be processed by any Thermal Series machines.

**Comment by RibozymeR** [comment]
Could not replicate TiC ores not being processed by Thermal machines, but fixed Thermal ores not being smeltable in a furnace!
