### ISSUE TITLE
Unstable Induced Tools cannot be cast

### ISSUE THREAD

**Issue by VeryPeeved** [Midnight145/blightfall-issue-tracker#48]
as the title says, the ingots (and blocks, which are much cheaper, if nerve wracking) will melt into a liquid without a proper name, and they cannot be poured into any of the casts, even the ingot one. it can only be used to make blocks.

There's a fix detailed here: 
https://github.com/rwtema/extrautilities_old_issues/issues/731#issuecomment-194673652
That shouldn't be hard to implement, although it doesn't fix it not having a proper name. But that's a small quibble.

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/f30e5c21f487733f49cbf95fda661828fccd0f51)
