### ISSUE TITLE
game crashed after playing for several hours, now won't start back up. 

### ISSUE THREAD

**Issue by Brettman130** [Midnight145/blightfall-issue-tracker#51]
[crash-2023-03-02_18.47.50-server.txt](https://github.com/Midnight145/blightfall-issue-tracker/files/10874226/crash-2023-03-02_18.47.50-server.txt)

I was working on infusing for the dawn machine and then it crashed and won't start my world again. It says there' s some backup data in use and to make a backup (which I did after the warning). Going past the warning by clicking 'yes', blightfall crashes. 

Do you have an idea how I can fix this?

**Comment by Midnight145** [comment]
resolved after discussing on the discord
