### ISSUE TITLE
Extra Utilities Spikes Schenanigans

### ISSUE THREAD

**Issue by ChargeRunner** [Midnight145/blightfall-issue-tracker#52]
The enchantment Capitalist, when placed on a weapon, is supposed to guarantee an emerald drop if a villager is killed by it. Spikes given this enchant will not make emeralds drop from villagers. The Educational enchant will also not give bonus experience when killing mobs with it.  Similarly, though I can not prove it, Looting seems to not affect spikes either, mobs seem to drop the normal amount of materials. The only enchants that seem to work properly are damage enhancing enchants (sharpness and wrath), and both work differently. Sharpness will never kill a mob in one hit no matter how much damage the mob takes, always leaving it with at least half a heart before killing it on the next hit (this is true for unenchanted spikes as well). Wrath on the other hand, will kill mobs in one hit if enough damage is taken. Diamond Spikes are completely broken, always reducing a mob to 1 heart and never killing them regardless of enchants. From some cursory searches, it seems that this part is due to the fact that diamond spikes are considered a diamond sword (unlike gold spikes for some reason) and iguana tweaks picks up on this and nerfs the damages appropriately. The "final" hit from both types of spikes (if the mob has 1hp left) will do heavy knockback, and in gold spikes' case will sometimes not kill (except with wrath). Edit: Whitelisting diamond swords in the Iguana config does fix all of these issues for diamond spikes, and I'm to assume the same would occur with golden swords for gold spikes. Unfortunately due to the nature of the mod this would not really be a useful solution since these tools are supposed to be blacklisted for the challenge, but it is useful to know.

**Comment by Midnight145** [comment]
Hmm, alright, will look into this. 

I haven't personally used spikes so I'm not too familiar with them and their enchantability/effects.
What file/config entries in IguanaTweaks did you have to change? There are other ways of nerfing diamond swords that I can do

**Comment by ChargeRunner** [comment]
The exact file is the "main" config file under the Iguanatinkertweaks section of the config. From there, you should see a line that says "# Swords that are excluded if the option to nerf non-tinkers swords is enabled." Adding diamond or gold swords by their in game id (eg. minecraft:diamond_sword) will exclude them from the iguana nerfs and make the spikes work correctly.
As for how the spikes work, I haven't read the code, but my best guess is that the spikes use their in-built damage up until the "final" hit (the mob would die from the hit) at which point the hit is swapped for a gold/diamond sword held by a fake player so that the mob correctly drops player only items and exp. Since this fake player is using a nerfed sword, it can't kill nor utilize loot affecting enchants on the sword. No clue as to why gold spikes work and diamond ones do not, but again, that's my best guess.

**Comment by Midnight145** [comment]
There's not really any elegant way to do this, so I'm closing this for now. May reopen this sometime in the future.
