### ISSUE TITLE
Potions of Inivisibility in inventory aren't detected to complete Paranormalist 'Invisibility' quest.

### ISSUE THREAD

**Issue by EnigmaticSpirit** [Midnight145/blightfall-issue-tracker#53]
As per the title. Running 3.0.6-CE, but with NEI updated to 2.3.39 and CoreTweaks updated to 0.3.0.3 (in hopes of fixing some crashes I'm getting which I suspect are to do with graphics drivers).

Clicking Manual submit with 4 invisibility potions in inventory doesn't complete the quest.

**Comment by EnigmaticSpirit** [comment]
Hah! And I just manually completed it with /hqm edit and threw out the 3 minute potions... 
I hope I have whatever ingredients are required for the 6 minute ones!

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/1b7519ec6805ac616bce1c3d9d3ace7cadfea62b)

**Comment by EnigmaticSpirit** [comment]
Thanks for sorting this (and for breathing new life into Blightfall in general!). New description makes things very clear.

**Comment by Midnight145** [comment]
No problem, I'm glad to do it!
