### ISSUE TITLE
Sojourner's Sash is spelled incorrectly

### ISSUE THREAD

**Issue by EnigmaticSpirit** [Midnight145/blightfall-issue-tracker#58]
The sojourner's sash is currently named as 'Soujourner's Sash'.

I went to the trouble of cloning the other repository, adding the appropriate lines to Botania.zs, and went to commit the change, but I don't actually have git installed on my PC...

Proposed fix:
```

//Spelling corrections
game.setLocalization("item.botania:travelBelt.name", "Sojourner's Sash");
```

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/01bd61d5710eac23844048fb84ec875df16c866c)
