### ISSUE TITLE
Dawn Machine only loads chunk with the main block

### ISSUE THREAD

**Issue by RibozymeR** [Midnight145/blightfall-issue-tracker#59]
If the Dawn Machine is on a chunk border, it will only load the chunk the central block is in

**Comment by Midnight145** [comment]
Might come back to this later, but for now I think that the chances of this happening, along with the area around it not being otherwise chunkloaded via chickenchunks or whatever (as the base would need chunkloaded for automation) is fairly slim, so for the most part I think it's a non-issue.
