### ISSUE TITLE
Completionist quest unlocked too early

### ISSUE THREAD

**Issue by Ryeoboy** [Midnight145/blightfall-issue-tracker#6]
Either the "find an ethereal bloom" quest or the scanner merit badge quest unlocked it.
Been told it's only supposed to unlock after the game has been beaten.

**Comment by Midnight145** [comment]
Fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/404be0f18f176b034bf2aed8fe228a5fc54b7d82) to blightfall-configs, will be fixed in next release.
