### ISSUE TITLE
Some stone under Alpha drop point should be Red Granite instead of Vanilla

### ISSUE THREAD

**Issue by litten8** [Midnight145/blightfall-issue-tracker#61]
There is some vanilla stone underneath the Alpha drop point, but all the ores that generate within it are red granite, indicating that it should be red granite, not vanilla stone. Attached is an image showing location, as well as two of the red granite veins within the stone.
![image](https://user-images.githubusercontent.com/20496976/230254351-813ecf38-62a4-4f37-96c6-26f2421db6ae.png)

**Comment by Midnight145** [comment]
Not really a good way to fix this unfortunately, and as it's not anything gamebreaking or serious, I think I'm just going to let it be to avoid breaking something

**Comment by kadirac** [comment]
This bug also occurs under the swamp in some areas (again, not gamebreaking or serious).
