### ISSUE TITLE
Possible Dawn Machine edge cases

### ISSUE THREAD

**Issue by amagnemite** [Midnight145/blightfall-issue-tracker#62]
After flying around Dawn Machine cleaned chunks, I noticed there were a handful of one block large tainted areas the Dawn Machine seemingly "missed". My only guess is that there's a small window of opportunity between the block cleansing and the mob cleansing where tainted sheep/possibly even Nodes managed to spread a bit of taint before being cleansed.

On a similar note, I've also noticed singular tainted mobs (sheep/pigs) in areas where mobs should have been cleansed, such as a tainted sheep amongst a herd of cleansed sheep. I'm much less certain on what the cause is here, possibly the mobs walking out of the currently cleansing chunk and into an unloaded, already cleansed chunk?

Unrelated to the other two, any chance the [writeup](https://github.com/Midnight145/blightbuster/blob/master/writeups/Dawn%20Machine%20Writeup.md) will be updated? Understandable if it won't be.

**Comment by tiflu** [comment]
I don't think this is really fixable without changing how the dawn machine functions entirely, again. yes, it's because there's a time gap between adjacent chunks being cleaned.

**Comment by Midnight145** [comment]
Hmm, I'm not entirely sure. Each chunk is only loaded for one tick, so in theory there isn't enough time for anything to trigger, but I'll look into it.

I might update the writeup eventually, but a lot of the numbers are the same tbh, just scaled up to account for an entire chunk instead of a single block

**Comment by Midnight145** [comment]
I'll add a config option that will force the dawn machine to go over every chunk a second time while cleaning, in case somehow something does happen in that one tick that it's loaded
