### ISSUE TITLE
Daily bonemeal quest now directing to random location under ground?

### ISSUE THREAD

**Issue by MayliSong** [Midnight145/blightfall-issue-tracker#65]
At some point, my quest book has started listing this location as requirement for the daily bonemeal. So now I can't get daily bonemeal it seems, since the Y coordinate is far below the top layer of blocks at the map there. 
![Screenshot_1](https://user-images.githubusercontent.com/63749441/234510621-1e32eff9-bcc1-4b57-b4b8-570d4ac32ce0.png)
![Screenshot_2](https://user-images.githubusercontent.com/63749441/234510649-4659885b-1d26-4ee3-bf99-d114528624f2.png)

**Comment by 84841** [comment]
I can confirm that something similar to this happened to me a day or so ago. The issue eventually resolved itself when I played another session later, but it wasn't fun missing out on my free daily bonemeal for a couple of in-game weeks.

**Comment by MayliSong** [comment]
Curse my ADHD for making me forget to reply here, but the above workaround does work for the time being: quitting to menu and launching again will fix whatever bug causes this, but doesn't stop it from potentially recurring later. I've had it happen at least one more time since.

**Comment by Midnight145** [comment]
I still have no idea what causes this, I've never found a consistent way to reproduce this
