### ISSUE TITLE
(Thaumcraft bug) Waypoints and food particles show behind taint instead of in front of it

### ISSUE THREAD

**Issue by kadirac** [Midnight145/blightfall-issue-tracker#67]
![Waypoint screenshot example](https://i.imgur.com/h4UjzXH.png)
![Food particle screenshot example](https://i.imgur.com/XZX56oi.png)

**Comment by Midnight145** [comment]
Unfortunately, I doubt there's much I can do about that, as it's a rendering issue with either Thaum or Minecraft. I'll leave it open for a bit in case anyone has any ideas. It's not a _major_ issue, so I'm not too worried about it though.

**Comment by tiflu** [comment]
I think it's a Minecraft issue with partial blocks. should be the same with a chest or anvil, you could try that. i know the healing axe does something similar in third person

**Comment by kadirac** [comment]
![Screenshot example](https://i.imgur.com/c75x05S.png)
Chests don't seem to have the same issue (if I'm interpreting your comment right).
