### ISSUE TITLE
[Meta] Standard users can't add labels to issues

### ISSUE THREAD

**Issue by kadirac** [Midnight145/blightfall-issue-tracker#68]

**Comment by Midnight145** [comment]
I looked into this already, and it looks like Git just doesn't support this, only contributors can add labels. If you figure out how I can do this, feel free to let me know. Also, if you'd like to be a contributor to any of the projects, feel free to reach out to me on Discord either via the [Blightfall discord](https://discord.gg/uj8Hfd3mrH) (if you aren't there already) or to me directly @ Midnight#0828

**Comment by RibozymeR** [comment]
Doesn't seem like we can do anything about this, as Github just doesn't provide this option. Closing this issue.
