### ISSUE TITLE
Add UBC cobblestone -> stone tool rod recipe

### ISSUE THREAD

**Issue by kadirac** [Midnight145/blightfall-issue-tracker#69]
Right now stone tool rods can only be made from vanilla cobblestone.

**Comment by RibozymeR** [comment]
Fixed in [this PR](https://github.com/Midnight145/blightfall-configs/pull/4)

**Comment by Midnight145** [comment]
Merged in [this commit](https://github.com/Midnight145/blightfall-configs/commit/e06f5c5cdef086906bae3e5dc2be4015f13fc6ef)
