### ISSUE TITLE
(Thaumcraft/UBC) Arcane Bore interaction bugs

### ISSUE THREAD

**Issue by ZWarriorKrillin** [Midnight145/blightfall-issue-tracker#75]
~~an Arcane Bore (Thaumcraft) fitted with Consuming (enchantment, FM) pickaxe will not delete UBC cobblestone types.~~

~~Bore fitted with Corrupting (enchantment, FM) pickaxe will not affect UBC infused stone ores.~~

Bore fitted with Silk Touch pickaxe or focus will harvest UBC ore blocks as themselves (for instance, giving Dacite Coal Ore instead of just, Coal Ore), which breaks recipes. 

EDIT: tested the FM enchantments more and they dont seem to work on normal stone\ore either, so thats a compatability issue on FMs end, not UBC

**Comment by Midnight145** [comment]
Seems to be an issue with the way UBC handles ore handling, which is closed source so there's not *too* much I can do
