### ISSUE TITLE
oredict Chisel mod marble to be interchangeable with the underground biomes marble

### ISSUE THREAD

**Issue by mihai-bontea** [Midnight145/blightfall-issue-tracker#77]

**Comment by Midnight145** [comment]
Unfortunately it looks like even with them oredict'd, you won't be able to chisel them directly. I added a crafting recipe, similar to the cobblestone crafting recipe, that will allow you to convert ub marble to chisel marble in [this commit](https://github.com/Midnight145/blightfall-configs/commit/3cc10015f7a64a0a0c3f96f79658bc2a6ff93362)
