### ISSUE TITLE
The Blightfall Server

### ISSUE THREAD

**Issue by Gurkk80** [Midnight145/blightfall-issue-tracker#78]
I am wanting to do a Blightfall series now that it is being updated, but it seems the provided server is not working and I can't find a download for a raw vanilla 1.7.10 server.

**Comment by Midnight145** [comment]
What's the error with the provided server?

**Comment by Gurkk80** [comment]
Everytime I try to run it, it spits out an error.

**Comment by Midnight145** [comment]
Yes, what is the error it spits out?

**Comment by Gurkk80** [comment]
D:\Servers\Blight Server>java -Dlog4j.configurationFile=log4j2_server.xml -Xmx3G -Xms2G -XX:MaxPermSize=128m -jar "Blightfall.jar" nogui
Unrecognized VM option 'MaxPermSize=128m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by Midnight145** [comment]
You need java 8, you're using something newer

**Comment by Gurkk80** [comment]
That is from trying to run the start.bat, Blightfall.jar doesn't work, and minecraft_server.1.7.10 just runs a vanilla server.

**Comment by Gurkk80** [comment]
Ah, okay

**Comment by Midnight145** [comment]
closing, if java 8 didn't fix feel free to reopen
