### ISSUE TITLE
Certain Custom Thaumcraft Research Pages Don't Have Proper Text

### ISSUE THREAD

**Issue by puncrafter** [Midnight145/blightfall-issue-tracker#8]
Some (most) of the custom research pages don't display their text properly. So far I've noticed blood magic's tier 6 integration, as well as the Dawn Machine and the Offering of Dawn, aren't working properly. The Dawn Charger works fine though.

![image](https://user-images.githubusercontent.com/53954921/216449536-ee16fbc0-02a0-4346-a70b-7215593d6262.png)

![image](https://user-images.githubusercontent.com/53954921/216449480-7a6b5230-6c4e-4fea-9b28-4d827f47907f.png)

**Comment by puncrafter** [comment]
This is what some of the pages look like.

![image](https://user-images.githubusercontent.com/53954921/216449746-0e63337a-56e0-40d5-a333-4903b21a3516.png)

**Comment by Midnight145** [comment]
Strange, minetweaker seems to be having an issue loading scripts. Run `/mt reload` and that should resolve itself.

**Comment by puncrafter** [comment]
Yeah that worked

**Comment by Midnight145** [comment]
alright!
