### ISSUE TITLE
Talisman of ring breaking

### ISSUE THREAD

**Issue by TopPercentageRattata** [Midnight145/blightfall-issue-tracker#81]
![Screenshot (891)](https://github.com/Midnight145/blightfall-issue-tracker/assets/16669193/506f44bc-56e1-489b-ad69-406702a74b7c)

**Comment by Midnight145** [comment]
https://github.com/Midnight145/ThaumicTinkerer/commit/5bdaf5ea92f9599fac0f704fda71dcc02dd79410
