### ISSUE TITLE
ships and dawn machine

### ISSUE THREAD

**Issue by tiflu** [Midnight145/blightfall-issue-tracker#82]
![image](https://github.com/Midnight145/blightfall-issue-tracker/assets/123897398/f22ce8d7-3867-4ce5-bb39-cf8524b3ae42)

**Comment by Midnight145** [comment]
fixed in [this commit](https://github.com/Midnight145/blightfall-configs/commit/f36037f925da0ba93ed19682e735b3a2a7d432a3)
