### ISSUE TITLE
Blood Magic Ritual of Magnetism Can't see UBC Variants of Vanilla Ores

### ISSUE THREAD

**Issue by drageuth** [Midnight145/blightfall-issue-tracker#84]
I attempted to create an automated mining system, combining Blood Magic's Ritual of Magnetism and Ritual of the Crusher.  The RoM is capable of digging up thaumcraft ores like the infused shards and amber, it's capable of digging up tech ores like tin and copper, and it's capable of digging up ores like Promethium, Oureclase, Adamantium, and so on.

However, it didn't pull a single piece of iron, gold, redstone, diamond....  

I put the rig over a spot I knew had iron, and watched it skip right over it. 

On further testing, I dug up one of the pieces of iron, thus turning it from the Underground Biomes Construct version of iron, to vanilla minecraft iron.  I put the vanilla ore back down.  When the RoM's scanning went over the area again, it took the vanilla iron, ignoring the UBC iron around it.

I know that the Ritual of Magnetism can work with all the UBC variants; it's finding all the mod ores, after all.  It just hasn't been pointed to the vanilla ores.  I'm not sure where in the configs and scripts you'd have to go to fix this.

**Comment by drageuth** [comment]
Following up, I've managed to hack together a fix around the issue.  Adding the UBC ores to the ore dictionary made them visible.  This is a copy of my hack-fix: https://www.dropbox.com/s/kkie81dh7jvifsh/BMagic%20Ore%20Fix.zs?dl=0 

putting that in the scripts file fixes the issue, for me

**Comment by Midnight145** [comment]
merged in [this commit](https://github.com/Midnight145/blightfall-configs/commit/f9020aa481e7656d669a983eff37b07a5e012449)
