### ISSUE TITLE
Infinite Heavy Cream through Cooking Table

### ISSUE THREAD

**Issue by Infinidoge** [Midnight145/blightfall-issue-tracker#88]
Using the cooking table to craft heavy cream while you have milk in your inventory (not in any kind of food storage) will create the cream without consuming the milk, allowing you to make infinite heavy cream at no cost.

(Wasn't sure if the mods used in CE are maintained for this version, so thought to report here.)

**Comment by tiflu** [comment]
Honestly, considering milk is incredibly easily renewable, and heavy cream is a pita to craft normally, i say we leave this one in

**Comment by Midnight145** [comment]
Unable to reproduce, can you send a video?

**Comment by Infinidoge** [comment]
Weird, I can't reproduce it now either. I have the large stack of heavy cream from when I did it, but trying it again now and it doesn't seem to be working. Must have been another factor at play.
![image](https://github.com/Midnight145/blightfall-issue-tracker/assets/22727114/fcb97109-a281-4f2f-aca3-cb48e2740d2a)

Closing the issue, but I'll reopen if I figure out a reproduction method.

**Comment by Midnight145** [comment]
Looks like you need to have a full inventory according to Space on the discord

**Comment by Infinidoge** [comment]
Aha! That's it!

https://github.com/Midnight145/blightfall-issue-tracker/assets/22727114/5516a276-5cb2-476d-8ff9-2141288a127e

**Comment by Midnight145** [comment]
not gonna bother fixing i don't think, updating to gtnh cfb didn't fix and I'm not gonna put the time into it
