### ISSUE TITLE
Improper display

### ISSUE THREAD

**Issue by Zeekmanzek** [Midnight145/blightfall-issue-tracker#9]
I'm not sure what's causing it but when I was playing Blightfall last week I had no display issues.
With this update, Both 3.0.0 and 3.0.1, whenever a world is generated I have to press Z to leave the Voxel Map Welcome Page but then the entire screen changes to one color. The colors change whenever I move around or look around. Pressing Esc will make the color darker and make the mouse appear but none of the buttons are visible. They are, however, still there as I've managed to click one and hear the audio of clicking a menu button. I've tried re-entering the world/save to see if the issue persists and it does. I've tried Survival, Creative, and Hardcore but no change.
![image](https://user-images.githubusercontent.com/124312511/216460814-bce04cc8-6602-4181-81c3-468bb3ceb8bc.png)
The color that projects over the entire screen seems to be from the lower left corner.
The reason I believe this is because when I press T the screen flashes between two colors.

**Comment by Midnight145** [comment]
This is an issue with Intel integrated graphics--go to this [link](https://www.intel.com/content/www/us/en/download/19344/685037/intel-graphics-windows-dch-drivers.html) and download and install version 30.0.101.1069.
