### ISSUE TITLE
QOL suggestion: Quick Stack

### ISSUE THREAD

**Issue by EnderCorePL** [Midnight145/blightfall-issue-tracker#90]
I suggest adding Quick Stack mod to the main build, it allows to quickly stack items to nearby chests with the press of a hotkey.

I've installed the mod and so far it doesn't cause any problems. Checked it for infection as well with Java detection tool. 

https://www.curseforge.com/minecraft/mc-mods/quick-stack/files?page=1&pageSize=20&version=1.7.10

**Comment by Midnight145** [comment]
Unplanned for now, may take another look in the future
